# #input ()

# name = input("Tell me your name")

# print(name)

# # int(string)

# age = int(input("What is your age?"))

# print(name)
# print(age + 5)

#age = 24
# age = int(input("What is your age?"))

# if age >= 21:
#     print ("you can drink")
# elif age < 18:
#     print ("Couple of more years pal")
# else:
#     print("you live somewhere weird")

# count = 0

# while count <= 10:
#     count += 1 #equivalent to count = count + 1
#     print ("The count is", count)

# print ("Done")

# answer = ''

# while answer != 'when':
#     answer = input('Say when: ')
#     answer = answer.lower()

# print ("Say Cheese")